#!/bin/sh

templates=$(dirname $0)/templates

infrastructure=$1

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "vsphere" ] ; then
  echo "usage: ./generate_deployment_manifest <aws|warden|vsphere> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/proxy-deployment.yml \
  $templates/proxy-jobs.yml \
  $templates/proxy-properties.yml \
  $templates/proxy-infrastructure-${infrastructure}.yml \
  $*
