---
blobstore:  
  provider: s3
  options:
    bucket_name: cf-release-blobs
# Ben's private bucket, replace with cf-release-blobs
#    bucket_name: proxy-release
#    endpoint: https://s3-eu-west-1.amazonaws.com